---
hosts:
- name: host-name
  ipaddresses: 192.168.1.1
  label: mgr, mon, osd, rgw  
services:
  monitor:
    count-per-host: 1
  manager:
    count-per-host: 1
  radosgw:
    - name: public
      port: 8888
      count-per-host: 1
    - name: private
      port: 8889
      count-per-host: 1
